apiVersion: apps/v1
kind: Deployment
metadata:
  name: titansops-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titansops
      component: worker
  template:
    metadata:
      labels:
        app: titansops
        component: worker
    spec:
      containers:
      - name: worker
        image: wackopsprodacr.azurecr.io/tops-worker:0.0.1
        command: ["celery"]
        args: ["-A", "titansops.app.celery_app", "worker", "-l", "info"]
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: FLASK_APP
          value: "titansops.app"
        - name: FLASK_DEBUG
          value: "false"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DATABASE_HOST
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tms-secret
              key: DJANGO_SECRET_KEY
        - name: REDIS_URL
          value: "redis://titansops-redis:6379/0"